### ISSUE TITLE
Make simulated pulse source have more than 1 line

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#107]
To be able to test end to end data analysis with calibration routines it would be nice to be able to set a set of pulse heights for simlated pulse source, instead of just 1.  Could just cycle through them for now.

**Comment by joefowler** [comment]
That makes sense. But I'd hate to add more and more configuration info to the GUI.

Suppose instead of making a single pulse of the requested size, we repeat a sequence of pulses that are size [0.6, 0.8, and 1.0] times the requested size? That would be the easiest. Would that meet your calibration needs?

**Comment by ggggggggg** [comment]
I suspect that would be fine. We could maybe add an API to change the sequence, but hardcode the sequence in dastard commander?
