### ISSUE TITLE
triggerBroker/triggerCounter crash

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#277]
A crash can occur when changing the number of channels that are triggering that has to do with counting the number of triggerCounter messages. The linked code below, line 224, is what causes the number of messages to vary.

https://github.com/usnistgov/dastard/blob/bda5d615efba30fc7a3a8372e957c49abbbfa7d4/group_trigger.go#L220-L229

Probably instead of using maps here, we should use arrays and always iterate over all channels? Then there would be not counting step, because it would always just be the length of the array.

**Comment by joefowler** [comment]
I don't understand how [this code in data_source.go](https://github.com/usnistgov/dastard/blob/bda5d615efba30fc7a3a8372e957c49abbbfa7d4/data_source.go#L360-L371) can not fill the `allTrigchanList` with one `triggerList` per channel in the `AnySource` object, yet that seems to be happening. Still working the problem...

**Comment by joefowler** [comment]
Aha! The problem is not above. It's in `func (tc *TriggerCounter) countNewTriggers` which can generate a variable number of messages. If data processing steps contain < 1 second of data (which is the usual case), then the logic works fine. But when a data chunk is 1.5 seconds long, and when 1 or more channels has no triggers (or at some rate < 1 trigger per second), then the triggering assumptions would fail. Stand by for a fix...
