### ISSUE TITLE
MixFraction should be reported by server

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#83]
In light of the comment about not wanting to save ChannelsWithProjectors, I thought of other things that the server should expose but we shouldn't save. MixFraction is one. We could add a new message with a name like "DETAILS" that isn't saved by viper. Then we could put stuff like this in it.

**Comment by joefowler** [comment]
Well, this is a good point. And in fact, we already have a set of message-names-not-to-be-saved in `client_updater.go`:

```go
// nosaveMessages is a set of message names that you don't save, because they
// contain no configuration that makes sense to preserve across runs of dastard.
var nosaveMessages = map[string]struct{}{
	"channelnames":  {},
	"alive":         {},
	"triggerrate":   {},
	"numberwritten": {},
	"newdastard":    {},
}
```

Because this is a set of tags, not a single message tag, we can make as many such message names as we like. (That is, we don't need to stuff everything into a "DETAILS" message.)

That's the good news. The bad news (#84) is that the behavior advertised in the comment above is not being implemented correctly.

Back to Mix Fraction: I only vaguely remember discussing this. We _could_ save mix fraction and restore it. Are you sure that we don't want to?

**Comment by ggggggggg** [comment]
I'm not sure about mix fraction restoring, I agree it could actually be useful. Maybe start with yes and see how it goes?

So maybe the right course of action it to just add new message types? `MIXFRACTION`, `CHANNELSWITHPROJECTORS`, others... and add them to `nosaveMessages`, rather than put them in `STATUS`. The annoying thing about that is you have to deal with the timing of when the messages are sent. For MixFraction and Projectors the API is to set them one channel at a time, so we couldn't just send the message after any API call. We could change the API to require sending them all at once.

**Comment by joefowler** [comment]
Yes, I see the problem.

I have never loved the API of calling the RPC server once per tiny action (like set one channel's mix fraction), because I have a sense that RPC calls are expensive in some way I can't express. I guess it feels like 240 of them might take longer than we want.

On the other hand, how do you set just one channel's mix if the API were changed so we set them all at once?? Another possible API would be that clients send 2 arrays: a list of channel indices and a list of corresponding mixes. Then you can send 240 together, or 1 or however many you wish to change. Then the dastard reports back with the _complete_ list of all 240 mix values. This is not identical to how we handle trigger settings, but it's similar. (The difference: with triggers, there's _only one_ trigger setting that's applied to all channels in the list of channel indices.)

Separate issue: is there (and should there be) a distinction between "mix = 0" and "mix is off"?

Here's one idea about this and related issues: we _could_ bundle MIXFRACTION (and other) messages such that you wait (say) 1 second after the message is ready but before sending the message. If another such message arrives during that wait time, then we cancel the first and start the wait again. (This is similar to how we handle saving the viper configuration file.) I think it would work, but I don't like the way it adds complexity to dastard and introduces an inevitable delay before clients find out "the truth".

**Comment by ggggggggg** [comment]
Separate issue: is there (and should there be) a distinction between "mix = 0" and "mix is off"? **I think no, there wouldn't be any difference in behavior, it just seems redundant**

I think an api like

```go
type Args struct {
    Channelndicies []int
    MixFractions []float64
}
``` 

would be fine. It seems a bit annoying for sending projectors because it will be a LARGE message, but who cares?

**Comment by ggggggggg** [comment]
It could also be

```go
type Args struct {
MixFractions []NullableMixFraction
}
type NullableMixFraction struct {
Set bool
MixFraction float64
}
```

Probably the previous wins based on similarity to trigger API.

**Comment by joefowler** [comment]
I made some progress on this. Not pushed to github yet, but I'll work on it further next week.
